version: '3.7'

services:
  postgres:
    container_name: prisma_2023
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-min33sky}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwe123}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
